server:
  port: 8074
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: biobac_user
    password: rvz!RJKw54qv3S5%
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: usersDemo
jwt:
  secret: b10bac_super_secret_key_which_is_long_enough_please_change
  expiration-ms: 86400000
  refresh-token:
    secret: b10bac_refresh_super_secret_key_which_is_long_enough_please_change
    expiration-ms: 604800000




