server:
  port: 8084
spring:
  jpa:
      hibernate:
        ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/production
    username: root
    password: gagulik014A!
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: usersProd
jwt:
  secret: b10bac_super_secret_key_which_is_long_enough_please_change
  expiration-ms: 86400000
  refresh-token:
    secret: b10bac_refresh_super_secret_key_which_is_long_enough_please_change
    expiration-ms: 604800000




